apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-eitan-perimeter81-task
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: configmap-eitan-perimeter81-task
data:
  deploy_mode:  {{ .Values.deploy_mode }}