apiVersion: v1
kind: Service
metadata:
  name: eitan-perimeter81-task-srv
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: eitan-perimeter81-task-srv
spec:
  type: NodePort
  ports:
    - port: 9996
      targetPort: 9996
      name: http
      protocol: TCP
      nodePort: {{ .Values.node_port}}
  externalTrafficPolicy: Cluster
  sessionAffinity: None
  selector:
    app.kubernetes.io/name: eitan-perimeter81-task-deploy